#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

proj_name=${VIRTUAL_ENV##*/}

mkdir -p public
mkdir -p logs
mkdir -p project
mkdir -p gems
touch project/README.md
pip freeze > project/requirements.txt
cd project
git init
echo "# $proj_name" > README.md
echo ".DS_Store" >> .gitignore
echo "*.pyc" >> .gitignore
